Escalation_Queue__c,LOB_Name__c,Name,Queue__c,Referred_to_Queue__c,Share_With_ReferredBy__c
Mortgage Escalation Queue,Mortgage,Mortgage,Mortgage,FALSE,FALSE
Grandbridge Escalation Queue,Grandbridge,Grandbridge,Grandbridge,FALSE,
IROC Escalation Queue,Insurance,Insurance,IROC,TRUE,
Association Services Escalation Queue,Association Services,Association Services,Association Services Queue,FALSE,TRUE
Merchant Services Escalation Queue,Merchant Services,Merchant Services,Merchant Services Queue,FALSE,
Payment Solutions Escalation Queue,Payment Solutions/Treasury,Payment Solutions/Treasury,,FALSE,
Community Bank Escalation Queue,Community Bank - Commercial Services,Community Bank - Commercial Services,Community Bank Queue,FALSE,
SSRC Escalation Queue,Scott & Stringfellow,Scott & Stringfellow,,FALSE,
Wealth Division Escalation Queue,Wealth Division,Wealth Division,Wealth Division Queue,FALSE,
Investment Services Escalation Queue,Investment Services,Investment Services,,FALSE,
Retirement & Institutional Escalation Qu,Institutional Svcs/SHDR,Institutional Svcs/SHDR,Retirement & Institutional Queue,FALSE,
CM - Money Center (Franchise) Escalation,Capital Markets -Money Center(Franchise),Capital Markets - Money Center,CM - Money Center (Franchise),TRUE,
Dealer Finance Escalation Queue,Dealer Finance,Dealer Finance,Dealer Finance,FALSE,
Debt Capital Markets Escalation Queue,Debt Capital Markets,Debt Capital Markets,Debt Capital Markets,FALSE,
Equity Capital Markets Escalation Queue,Equity Capital Markets,Equity Capital Markets,Equity Capital Markets,FALSE,
Regional Acceptance Escalation Queue,Regional Acceptance Corporation,Regional Acceptance Corporation,Regional Acceptance,FALSE,
