Name,Queue_Name__c
B57876,Capital Markets Fix Referral Center
B01007,Payroll Service Referral Center
B03706,Scott & Stringfellow Referral Center
CCWL01,Wealth Lending Referral Center
WM0001,Wealth Management Referral Center
B57809,Asset Management Referral Center
B03704,Capital Markets Referral Center
B80549,IROC – Insurance Referral Center
C00137,Merchant Service Referral Center
CCBS01,Referral Center - Association Services
CHMD01,Mortgage Referral Center
