EndPoint__c,Name
https://ssdpep.bbt.com:8443/TIBCO_CAPITALIQ_DEV/Processes/ProcessStarters/CapIQService.serviceagent/CapitalIQPortEndpoint1,CAPIQ
https://ssdpep.bbt.com:8443/TIBCO_RCM_TESTE/Processes/ProcessStarters/SOAPProcessStarters/ContactMaintForSalesforceService.serviceagent/ContactMaintForSalesforceEndpoint1,RCM
https://ssdpep.bbt.com:8443/TIBCO_PRT_DEV/Processes/ProcessStarters/SOAPStarters/SOAPClientProblemSummary,ProblemManagement
https://ssdpep.bbt.com:8443/TIBCO_PRT_DEV/Processes/ProcessStarters/SOAPStarters/SOAPProblemDetail,ProblemDetail
